@php($kind = \App\Domain\Obligations\ObligationKind::from($obligationKind))
@php($categoryOptions = $kind->categoryOptions())
<div class="space-y-5" wire:key="obligation-fields-{{ $obligationKind }}">
    <div class="grid gap-5 sm:grid-cols-2">
        <flux:select wire:model="direction" label="Direction"><flux:select.option value="payable">I need to pay / return / do it</flux:select.option><flux:select.option value="receivable">Someone owes / must return / do it for me</flux:select.option></flux:select>
        <flux:select wire:model.live="obligationKind" label="What is owed?"><flux:select.option value="money">Money</flux:select.option><flux:select.option value="asset">Asset or item</flux:select.option><flux:select.option value="service">Service or time</flux:select.option><flux:select.option value="action">Action or commitment</flux:select.option></flux:select>
    </div>
    <p class="-mt-2 text-sm text-zinc-500">A single record can contain several obligations. Keep each promise, item, service, or money component separate so progress and evidence stay clear.</p>
    <div class="grid gap-5 sm:grid-cols-2">
        <flux:input wire:model="obligationTitle" label="Obligation title" placeholder="e.g. Money borrowed, gold bracelet, or repair work" required />
        <div>
            <flux:select wire:model="category" :label="$kind->categoryFieldLabel()" required>
                @foreach ($categoryOptions as $value => $label)
                    <flux:select.option value="{{ $value }}">{{ $label }}</flux:select.option>
                @endforeach
            </flux:select>
            <p class="mt-2 text-xs leading-5 text-zinc-500 dark:text-zinc-400">{{ $kind->categoryHelpText() }}</p>
        </div>
    </div>

    @if ($obligationKind === 'money')
        <div class="rounded-lg border border-sky-200 bg-sky-50 p-4 dark:border-sky-900/60 dark:bg-sky-950/30">
            <flux:select wire:model.live="trackingMode" label="How do you want to start tracking it?"><flux:select.option value="snapshot">Snapshot — start from the balance I know now</flux:select.option><flux:select.option value="ledger">Detailed ledger — record every movement from the start</flux:select.option></flux:select>
            <p class="mt-2 text-sm text-sky-900/70 dark:text-sky-100/70">Currency is selected from the supported list. Different movement currencies remain separate; there is no silent exchange-rate conversion.</p>
        </div>
        <div class="grid gap-5 sm:grid-cols-2"><flux:input wire:model="currentTotalBalance" type="number" step="any" min="0" label="{{ $trackingMode === 'ledger' ? 'Opening balance ('.$currency.')' : 'Current balance now ('.$currency.')' }}" :required="$trackingMode === 'snapshot'" /><flux:select wire:model.live="currency" label="Currency" required>@foreach (\App\Domain\Money\Currency::options() as $code => $label)<flux:select.option value="{{ $code }}">{{ $code }} — {{ $label }}</flux:select.option>@endforeach</flux:select></div>
        <div class="grid gap-5 sm:grid-cols-3"><flux:input wire:model="originalAmount" type="number" step="any" min="0" label="Original amount ({{ $currency }}, optional)" /><flux:input wire:model="minimumPaymentAmount" type="number" step="any" min="0" label="Minimum payment ({{ $currency }})" /><flux:input wire:model="nextDueOn" type="date" label="Next due date" /></div>
        <flux:checkbox wire:model="isInterestBearing" label="Interest, profit rate, or storage charges apply" />
    @elseif ($obligationKind === 'asset')
        <div class="rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900 dark:border-amber-900/60 dark:bg-amber-950/30 dark:text-amber-200">Use this for gold, a vehicle, equipment, a document, a digital item, access, or anything that must be returned or replaced. Estimated value is context, not a money balance.</div>
        <div class="grid gap-5 sm:grid-cols-2"><flux:input wire:model="subjectName" label="Asset or item" placeholder="e.g. 916 gold bracelet, Toyota Vios, passport" required /><flux:select wire:model="assetType" label="Asset type"><flux:select.option value="physical">Physical item</flux:select.option><flux:select.option value="document">Document</flux:select.option><flux:select.option value="digital">Digital item or data</flux:select.option><flux:select.option value="access">Access or credential</flux:select.option><flux:select.option value="other">Other asset</flux:select.option></flux:select></div>
        <div class="grid gap-5 sm:grid-cols-2"><flux:select wire:model.live="quantityMode" label="How should quantity work?"><flux:select.option value="countable">Whole units — 1 camera, 2 chairs</flux:select.option><flux:select.option value="measurable">Measurable — 0.5 kg, 2.5 hours</flux:select.option></flux:select><div class="rounded-lg bg-amber-50 px-4 py-3 text-sm text-amber-900 dark:bg-amber-950/30 dark:text-amber-200">Choose whole units for complete items. Choose measurable only when the subject is naturally weighed, measured, or timed.</div></div>
        <div class="grid gap-5 sm:grid-cols-3"><flux:input wire:model="subjectQuantity" type="number" step="{{ $quantityMode === 'countable' ? '1' : '0.0001' }}" min="{{ $quantityMode === 'countable' ? '1' : '0.0001' }}" label="Outstanding quantity" required /><flux:input wire:model="subjectUnit" label="Unit" placeholder="item, gram, set" required /><flux:select wire:model="subjectCondition" label="Condition"><flux:select.option value="">Not recorded</flux:select.option><flux:select.option value="new">New</flux:select.option><flux:select.option value="good">Good</flux:select.option><flux:select.option value="fair">Fair</flux:select.option><flux:select.option value="damaged">Damaged</flux:select.option></flux:select></div>
        <div class="grid gap-5 sm:grid-cols-3"><flux:input wire:model="nextDueOn" type="date" label="Return by (optional)" /><flux:input wire:model="estimatedValue" type="number" step="any" min="0" label="Estimated value ({{ $estimatedValueCurrency }})" /><flux:select wire:model.live="estimatedValueCurrency" label="Value currency">@foreach (\App\Domain\Money\Currency::options() as $code => $label)<flux:select.option value="{{ $code }}">{{ $code }} — {{ $label }}</flux:select.option>@endforeach</flux:select></div>
        <flux:textarea wire:model="subjectDetails" label="Asset details" placeholder="Serial number, size, colour, registration, weight, identifying marks, or replacement terms." rows="3" />
    @elseif ($obligationKind === 'service')
        <div class="rounded-lg border border-teal-200 bg-teal-50 p-4 text-sm text-teal-950 dark:border-teal-900/60 dark:bg-teal-950/30 dark:text-teal-200">Use this for work, care, transport, professional help, or time owed. Add a quantity when the service can be measured.</div>
        <div class="grid gap-5 sm:grid-cols-2"><flux:input wire:model="subjectName" label="Service or work" placeholder="e.g. 12 hours of repair work, childcare, consultation" required /><flux:select wire:model="serviceType" label="Service type"><flux:select.option value="time">Time or hours</flux:select.option><flux:select.option value="skilled_work">Skilled work</flux:select.option><flux:select.option value="care">Care or responsibility</flux:select.option><flux:select.option value="transport">Transport or delivery</flux:select.option><flux:select.option value="professional">Professional service</flux:select.option><flux:select.option value="other">Other service</flux:select.option></flux:select></div>
        <div class="grid gap-5 sm:grid-cols-2"><flux:select wire:model.live="quantityMode" label="How should quantity work?"><flux:select.option value="countable">Whole units — 1 visit, 2 jobs</flux:select.option><flux:select.option value="measurable">Measurable — 0.5 hours, 2.5 days</flux:select.option></flux:select><div class="rounded-lg bg-teal-50 px-4 py-3 text-sm text-teal-950 dark:bg-teal-950/30 dark:text-teal-200">Use measurable for time or a scale. Use whole units for discrete visits, jobs, or deliveries.</div></div>
        <div class="grid gap-5 sm:grid-cols-2"><flux:input wire:model="subjectQuantity" type="number" step="{{ $quantityMode === 'countable' ? '1' : '0.0001' }}" min="{{ $quantityMode === 'countable' ? '1' : '0.0001' }}" label="Quantity (optional)" /><flux:input wire:model="subjectUnit" label="Unit" placeholder="hours, days, visits, jobs" /></div>
        <flux:textarea wire:model="completionCriteria" label="What does completion look like?" rows="3" /><flux:textarea wire:model="subjectDetails" label="Service details" rows="3" /><flux:input wire:model="nextDueOn" type="date" label="Due date (optional)" />
    @else
        <div class="rounded-lg border border-violet-200 bg-violet-50 p-4 text-sm text-violet-900 dark:border-violet-900/60 dark:bg-violet-950/30 dark:text-violet-200">Use this for a promise, deliverable, responsibility, confidentiality commitment, or agreement outcome.</div>
        <flux:textarea wire:model="completionCriteria" label="What does completion look like?" placeholder="e.g. Submit the signed document, delete all copies, and confirm by email." rows="4" required /><flux:input wire:model="nextDueOn" type="date" label="Due date (optional)" />
    @endif
    <div class="rounded-lg border border-zinc-200 p-4 dark:border-zinc-700"><flux:checkbox wire:model.live="isConditional" label="This obligation only applies after a condition or event" />@if ($isConditional)<div class="mt-4 space-y-4"><flux:textarea wire:model="conditionDescription" label="What must happen first?" rows="3" required /><flux:input wire:model="conditionTriggeredOn" type="date" label="Condition triggered on (optional)" /></div>@endif</div>
    <flux:textarea wire:model="description" label="Obligation notes" placeholder="Specific agreement context, background, or details needing confirmation." rows="3" />
</div>
