<div class="mx-auto w-full max-w-3xl">
    <div class="mb-7">
        <a wire:navigate href="{{ route('records.show', $obligation->record) }}" class="text-sm text-zinc-500 hover:text-zinc-800 dark:hover:text-zinc-200">← Back to record</a>
        <div class="mt-5 flex items-start gap-4"><span class="app-page-icon hidden shrink-0 sm:inline-flex"><flux:icon name="document-text" class="size-6" /></span><div><div class="app-eyebrow">Obligation details</div><flux:heading size="xl" class="mt-2 text-3xl tracking-tight">Edit obligation</flux:heading><flux:text class="mt-2 leading-6">Update the facts and terms you know. Fulfillment history remains in the timeline.</flux:text></div></div>
    </div>

    <form wire:submit="save" novalidate class="app-card space-y-7 rounded-2xl p-6 sm:p-7">
        <div class="rounded-lg bg-zinc-50 px-4 py-3 text-sm text-zinc-600 dark:bg-zinc-800 dark:text-zinc-300">{{ $obligation->direction === 'payable' ? 'To pay / return / do' : 'To receive / get back / have done' }} · {{ $obligation->kindLabel() }} · Type cannot be changed after creation.</div>
        <div class="grid gap-5 sm:grid-cols-2"><flux:input wire:model="title" label="Obligation title" required /><div><flux:select wire:model="category" :label="$obligation->kind()->categoryFieldLabel()" required>@foreach ($obligation->kind()->categoryOptions() as $value => $label)<flux:select.option value="{{ $value }}">{{ $label }}</flux:select.option>@endforeach</flux:select><p class="mt-2 text-xs leading-5 text-zinc-500 dark:text-zinc-400">{{ $obligation->kind()->categoryHelpText() }}</p></div></div>

        @if ($obligationKind === 'money')
            <div class="rounded-lg border border-sky-200 bg-sky-50 p-4 dark:border-sky-900/60 dark:bg-sky-950/30"><flux:select wire:model.live="trackingMode" label="Tracking mode">@if (! $hasTransactions)<flux:select.option value="snapshot">Snapshot — start from a known balance</flux:select.option>@endif<flux:select.option value="ledger">Detailed ledger — dated balance movements</flux:select.option></flux:select><p class="mt-2 text-sm text-sky-900/70 dark:text-sky-100/70">{{ $hasTransactions ? 'Movement history is active, so this record stays ledger-driven. Use an adjustment to correct its balance.' : 'A snapshot can accept a first movement; after that, ledger movements are the source of truth.' }}</p></div>
            <div class="grid gap-5 sm:grid-cols-2"><div><flux:input wire:model="currentTotalBalance" type="number" step="any" min="0" label="{{ $trackingMode === 'ledger' ? 'Current balance (use a movement to change)' : 'Current total balance ('.$obligation->currency.')' }}" :disabled="$trackingMode === 'ledger'" /><p class="mt-1 text-xs text-zinc-500">{{ $trackingMode === 'ledger' ? 'Record an adjustment when correcting the balance.' : 'The amount still outstanding today. Stored as the currency’s minor unit.' }}</p></div><flux:input wire:model="currentPrincipalBalance" type="number" step="any" min="0" label="Principal balance ({{ $obligation->currency }})" :disabled="$trackingMode === 'ledger'" /></div>
            <div class="grid gap-5 sm:grid-cols-2"><flux:input wire:model="originalAmount" type="number" step="any" min="0" label="Original amount ({{ $obligation->currency }}, optional)" /><flux:input wire:model="minimumPaymentAmount" type="number" step="any" min="0" label="Minimum payment ({{ $obligation->currency }})" /></div>
            <flux:checkbox wire:model="isInterestBearing" label="This record has interest, profit rate, or storage charges" />
        @elseif ($obligationKind === 'asset')
            <div class="rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900 dark:border-amber-900/60 dark:bg-amber-950/30 dark:text-amber-200">The outstanding quantity is changed through asset events. Editing this form changes the description, not the fulfillment ledger.</div>
            <div class="grid gap-5 sm:grid-cols-2"><flux:input wire:model="subjectName" label="What asset or item is owed?" required /><flux:select wire:model="assetType" label="Asset type"><flux:select.option value="physical">Physical item</flux:select.option><flux:select.option value="document">Document</flux:select.option><flux:select.option value="digital">Digital item or data</flux:select.option><flux:select.option value="access">Access or credential</flux:select.option><flux:select.option value="other">Other asset</flux:select.option></flux:select></div>
            <div class="grid gap-5 sm:grid-cols-2"><flux:select wire:model.live="quantityMode" label="How should quantity work?"><flux:select.option value="countable">Whole units — 1 camera, 2 chairs</flux:select.option><flux:select.option value="measurable">Measurable — 0.5 kg, 2.5 hours</flux:select.option></flux:select><div class="rounded-lg bg-amber-50 px-4 py-3 text-sm text-amber-900 dark:bg-amber-950/30 dark:text-amber-200">Whole-unit items cannot use a fractional quantity. Choose measurable only for something naturally weighed or measured.</div></div>
            <div class="grid gap-5 sm:grid-cols-3"><flux:input wire:model="subjectQuantity" type="number" step="{{ $quantityMode === 'countable' ? '1' : '0.0001' }}" min="{{ $quantityMode === 'countable' ? '1' : '0.0001' }}" label="Opening quantity" required /><flux:input wire:model="currentSubjectQuantity" type="number" step="{{ $quantityMode === 'countable' ? '1' : '0.0001' }}" min="0" label="Currently outstanding" :disabled="! $quantityNeedsReconciliation" /><flux:input wire:model="subjectUnit" label="Unit" required /></div>
            @if ($quantityNeedsReconciliation)<div class="rounded-lg border border-rose-200 bg-rose-50 px-4 py-3 text-sm leading-6 text-rose-800 dark:border-rose-900/60 dark:bg-rose-950/30 dark:text-rose-200"><strong>Quantity needs reconciliation.</strong> This record contains a fractional whole-unit value from earlier history. Set the currently outstanding quantity to a whole number, then save. The timeline remains unchanged.</div>@endif
            <div class="grid gap-5 sm:grid-cols-3"><flux:select wire:model="subjectCondition" label="Condition"><flux:select.option value="">Not recorded</flux:select.option><flux:select.option value="new">New</flux:select.option><flux:select.option value="good">Good</flux:select.option><flux:select.option value="fair">Fair</flux:select.option><flux:select.option value="damaged">Damaged</flux:select.option></flux:select><flux:input wire:model="estimatedValue" type="number" step="any" min="0" label="Estimated value (optional)" /><flux:select wire:model="estimatedValueCurrency" label="Value currency">@foreach (\App\Domain\Money\Currency::options() as $code => $label)<flux:select.option value="{{ $code }}">{{ $code }} — {{ $label }}</flux:select.option>@endforeach</flux:select></div>
            <flux:textarea wire:model="subjectDetails" label="Asset details" rows="4" />
        @elseif ($obligationKind === 'service')
            <div class="rounded-lg border border-teal-200 bg-teal-50 p-4 text-sm text-teal-950 dark:border-teal-900/60 dark:bg-teal-950/30 dark:text-teal-200">If a quantity is recorded, progress events reduce it and added-scope events increase it. Otherwise use progress and fulfillment notes.</div>
            <div class="grid gap-5 sm:grid-cols-2"><flux:input wire:model="subjectName" label="What service or work is owed?" required /><flux:select wire:model="serviceType" label="Service type"><flux:select.option value="time">Time or hours</flux:select.option><flux:select.option value="skilled_work">Skilled work</flux:select.option><flux:select.option value="care">Care or responsibility</flux:select.option><flux:select.option value="transport">Transport or delivery</flux:select.option><flux:select.option value="professional">Professional service</flux:select.option><flux:select.option value="other">Other service</flux:select.option></flux:select></div>
            <div class="grid gap-5 sm:grid-cols-2"><flux:select wire:model.live="quantityMode" label="How should quantity work?"><flux:select.option value="countable">Whole units — 1 visit, 2 jobs</flux:select.option><flux:select.option value="measurable">Measurable — 0.5 hours, 2.5 days</flux:select.option></flux:select><div class="rounded-lg bg-teal-50 px-4 py-3 text-sm text-teal-950 dark:bg-teal-950/30 dark:text-teal-200">Use measurable for time or a scale. Use whole units for discrete visits, jobs, or deliveries.</div></div>
            <div class="grid gap-5 sm:grid-cols-2"><flux:input wire:model="subjectQuantity" type="number" step="{{ $quantityMode === 'countable' ? '1' : '0.0001' }}" min="0.0001" label="Opening quantity (optional)" /><flux:input wire:model="subjectUnit" label="Unit" placeholder="hours, days, visits, jobs" /></div>
            <flux:textarea wire:model="completionCriteria" label="What does completion look like?" rows="4" />
            <flux:textarea wire:model="subjectDetails" label="Service details" rows="4" />
        @else
            <div class="rounded-lg border border-violet-200 bg-violet-50 p-4 text-sm text-violet-900 dark:border-violet-900/60 dark:bg-violet-950/30 dark:text-violet-200">Use the timeline for progress, missed commitments, scope changes, and fulfillment.</div>
            <flux:textarea wire:model="completionCriteria" label="What does completion look like?" rows="4" required />
        @endif

        <div class="grid gap-5 sm:grid-cols-2"><flux:input wire:model="startedOn" type="date" label="Started" /><flux:input wire:model="dueOn" type="date" label="Final due date" /></div>
        <flux:input wire:model="nextDueOn" type="date" label="Next due date (optional)" />
        <flux:select wire:model="dataConfidence" label="How certain are these details?"><flux:select.option value="verified">Verified</flux:select.option><flux:select.option value="partial">Partially known</flux:select.option><flux:select.option value="estimated">Estimated</flux:select.option></flux:select>

        <div class="rounded-lg border border-zinc-200 p-4 dark:border-zinc-700"><flux:checkbox wire:model.live="isConditional" label="This obligation only applies after a condition or event" />@if ($isConditional)<div class="mt-4 space-y-4"><flux:textarea wire:model="conditionDescription" label="What must happen first?" rows="3" required /><flux:input wire:model="conditionTriggeredOn" type="date" label="Condition triggered on (optional)" /></div>@endif</div>
        <flux:textarea wire:model="description" label="General notes" rows="4" />
        <div class="flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><flux:button :href="route('records.show', $obligation->record)" wire:navigate variant="ghost">Cancel</flux:button><flux:button type="submit" variant="primary">Save changes</flux:button></div>
    </form>
</div>
