<section class="rounded-xl border border-zinc-200 bg-white dark:border-zinc-700 dark:bg-zinc-900">
    <div class="border-b border-zinc-200 px-5 py-4 dark:border-zinc-700"><flux:heading size="lg">Add terms version</flux:heading><flux:text class="mt-1 text-sm">Keep the original agreement details visible and explainable.</flux:text></div>
    <form wire:submit="save" class="space-y-5 px-5 py-5">
        <flux:select wire:model.live="calculationMethod" label="Calculation method"><flux:select.option value="none">No additional calculation</flux:select.option><flux:select.option value="simple_interest">Fixed simple interest</flux:select.option><flux:select.option value="compound_interest">Compounding interest</flux:select.option><flux:select.option value="storage_fee">Recurring storage fee</flux:select.option><flux:select.option value="fixed_installment">Fixed instalment</flux:select.option></flux:select>
        <div class="grid gap-5 sm:grid-cols-3"><flux:input wire:model="interestRate" type="number" step="0.00000001" min="0" label="Interest rate (%)" /><flux:select wire:model="interestPeriod" label="Rate period"><flux:select.option value="annual">Annual</flux:select.option><flux:select.option value="monthly">Monthly</flux:select.option><flux:select.option value="weekly">Weekly</flux:select.option></flux:select><flux:select wire:model="compoundingPeriod" label="Compounds"><flux:select.option value="">Simple / none</flux:select.option><flux:select.option value="monthly">Monthly</flux:select.option><flux:select.option value="weekly">Weekly</flux:select.option><flux:select.option value="daily">Daily</flux:select.option></flux:select></div>
        <div class="grid gap-5 sm:grid-cols-2"><flux:input wire:model="storageFeeAmount" type="number" step="any" min="0" label="Storage fee ({{ $obligation->currency }})" /><flux:select wire:model="storageFeePeriod" label="Storage period"><flux:select.option value="monthly">Monthly</flux:select.option><flux:select.option value="weekly">Weekly</flux:select.option><flux:select.option value="daily">Daily</flux:select.option></flux:select></div>
        <div class="grid gap-5 sm:grid-cols-2"><flux:input wire:model="lateFeeAmount" type="number" step="any" min="0" label="Fixed late fee ({{ $obligation->currency }})" /><flux:input wire:model="lateFeeRate" type="number" step="0.00000001" min="0" label="Late fee rate (%)" /></div>
        <div class="grid gap-5 sm:grid-cols-2"><flux:input wire:model="gracePeriodDays" type="number" min="0" max="365" label="Grace period (days)" /><flux:checkbox wire:model="lateFeeRecurring" label="Apply late fee each overdue period" /></div>
        @if ($calculationMethod === 'fixed_installment')
            <div class="rounded-xl border border-sky-200 bg-sky-50/70 p-4 dark:border-sky-900/60 dark:bg-sky-950/30"><flux:input wire:model="fixedInstallmentAmount" type="number" step="any" min="0" label="Fixed instalment amount ({{ $obligation->currency }})" required /><p class="mt-2 text-xs text-sky-900/70 dark:text-sky-100/70">This records the agreed instalment amount. Use Schedule separately if you also want reminders or authorised payments.</p></div>
        @endif
        <flux:input wire:model="effectiveFrom" type="date" label="Effective from" required />
        <flux:textarea wire:model="sourceNote" label="Source or assumptions" rows="3" placeholder="Optional note about the agreement, statement, or estimate" />
        <flux:checkbox wire:model="sourceVerified" label="These terms were checked against evidence" />
        <flux:button type="submit" variant="primary" class="w-full">Save terms version</flux:button>
    </form>
</section>
