<section class="rounded-xl border border-zinc-200 bg-white dark:border-zinc-700 dark:bg-zinc-900">
    <div class="border-b border-zinc-200 px-5 py-4 dark:border-zinc-700"><flux:heading size="lg">Payment instructions</flux:heading><flux:text class="mt-1 text-sm">Choose which saved destination to use for this money obligation. The instruction keeps a snapshot, so later directory changes do not rewrite history; it never moves money by itself.</flux:text></div>
    @if (session('payment-instruction-created'))<div class="mx-5 mt-5 rounded-lg bg-emerald-50 px-4 py-3 text-sm text-emerald-800">{{ session('payment-instruction-created') }}</div>@endif
    @forelse ($instructionsList as $instruction)
        <div class="flex items-start justify-between gap-3 border-b border-zinc-100 px-5 py-4 last:border-0 dark:border-zinc-800"><div><div class="font-medium">{{ $instruction->paymentDestination?->label ?? 'Saved destination' }}</div><div class="mt-1 text-sm text-zinc-500">{{ $instruction->paymentDestination ? ucfirst(str_replace('_', ' ', $instruction->paymentDestination->method)) : 'Destination' }}@if ($instruction->paymentDestination?->provider) · {{ $instruction->paymentDestination->provider }}@endif @if ($instruction->currency) · {{ $instruction->currency }}@endif</div>@if ($instruction->beneficiary)<div class="mt-1 text-xs text-zinc-500">Beneficiary: {{ $instruction->beneficiary->preferred_name }}</div>@endif @if ($instruction->payee)<div class="mt-1 text-xs text-zinc-500">Payee: {{ $instruction->payee->preferred_name }}</div>@endif @if ($instruction->reference)<div class="mt-1 text-xs text-zinc-500">Reference: {{ $instruction->reference }}</div>@endif</div><flux:button size="sm" variant="ghost" wire:click="archive('{{ $instruction->id }}')" wire:confirm="Archive this payment instruction?">Archive</flux:button></div>
    @empty
        <div class="px-5 py-5 text-sm text-zinc-500">No payment instruction saved yet.</div>
    @endforelse
    <form wire:submit="save" class="grid gap-4 border-t border-zinc-200 px-5 py-5 sm:grid-cols-2 dark:border-zinc-700">
        <flux:select wire:model="paymentDestinationId" label="Destination"><flux:select.option value="">No destination selected</flux:select.option>@foreach ($destinations as $destination)<flux:select.option value="{{ $destination['id'] }}">{{ $destination['label'] }}</flux:select.option>@endforeach</flux:select>
        <flux:select wire:model="currency" label="Currency"><flux:select.option value="">Obligation currency</flux:select.option>@foreach (\App\Domain\Money\Currency::codes() as $code)<flux:select.option value="{{ $code }}">{{ $code }}</flux:select.option>@endforeach</flux:select>
        <flux:select wire:model="beneficiaryPartyId" label="Beneficiary (optional)"><flux:select.option value="">No beneficiary selected</flux:select.option>@foreach ($parties as $party)<flux:select.option value="{{ $party->id }}">{{ $party->preferred_name }}</flux:select.option>@endforeach</flux:select>
        <flux:select wire:model="payeePartyId" label="Payee (optional)"><flux:select.option value="">No payee selected</flux:select.option>@foreach ($parties as $party)<flux:select.option value="{{ $party->id }}">{{ $party->preferred_name }}</flux:select.option>@endforeach</flux:select>
        <div class="sm:col-span-2"><flux:input wire:model="reference" label="Reference (optional)" placeholder="e.g. March instalment" /></div>
        <div class="sm:col-span-2 flex justify-end"><flux:button type="submit" variant="primary">Save payment instruction</flux:button></div>
    </form>
</section>
