<section class="rounded-xl border border-zinc-200 bg-white dark:border-zinc-700 dark:bg-zinc-900">
    <div class="border-b border-zinc-200 px-5 py-4 dark:border-zinc-700"><flux:heading size="lg">{{ $obligation->kind()->isMoney() ? 'Record collection context' : 'Record fulfillment update' }}</flux:heading><flux:text class="mt-1 text-sm">{{ $obligation->kind()->isMoney() ? 'Keep a dated explanation for a missed, delayed, promised, or unusual collection. This does not change the balance.' : 'Keep a dated trail for this obligation. Add evidence after saving when needed.' }}</flux:text></div>
    <form wire:submit="save" novalidate class="space-y-5 px-5 py-5">
        @if ($obligation->kind()->isMoney())
            <flux:select wire:model.live="eventType" label="What happened?"><flux:select.option value="context">Context or circumstance</flux:select.option><flux:select.option value="missed">Expected collection missed</flux:select.option><flux:select.option value="postponed">Collection postponed</flux:select.option><flux:select.option value="promised">New payment promise</flux:select.option><flux:select.option value="note">General note</flux:select.option></flux:select>
        @elseif ($obligation->kind()->value === 'asset')
            <flux:select wire:model.live="eventType" label="Update type"><flux:select.option value="added">Additional asset owed</flux:select.option><flux:select.option value="returned">Returned in full</flux:select.option><flux:select.option value="partially_returned">Partially returned</flux:select.option><flux:select.option value="replaced">Replaced</flux:select.option><flux:select.option value="lost">Lost / not recoverable</flux:select.option><flux:select.option value="condition_update">Condition update</flux:select.option><flux:select.option value="waived">Waived / no longer required</flux:select.option><flux:select.option value="note">Note</flux:select.option></flux:select>
            @if (in_array($eventType, ['added', 'returned', 'partially_returned', 'replaced'], true))<div><flux:input wire:model="quantity" type="number" step="{{ $obligation->quantityMode()->inputStep() }}" min="{{ $obligation->quantityMode()->isCountable() ? '1' : '0.0001' }}" label="Quantity" /><p class="mt-1 text-xs text-zinc-500">Currently outstanding: {{ \App\Domain\Money\Decimal::display($obligation->current_subject_quantity) }} {{ $obligation->subject_unit }} · {{ $obligation->quantityMode()->isCountable() ? 'whole units only' : 'fractional quantities allowed' }}</p></div>@endif
        @elseif ($obligation->kind()->value === 'service')
            <flux:select wire:model.live="eventType" label="Update type"><flux:select.option value="added">Additional scope added</flux:select.option><flux:select.option value="progress">Progress delivered</flux:select.option><flux:select.option value="fulfilled">Fulfilled</flux:select.option><flux:select.option value="missed">Missed / delayed</flux:select.option><flux:select.option value="scope_change">Scope changed</flux:select.option><flux:select.option value="waived">Waived / no longer required</flux:select.option><flux:select.option value="note">Note</flux:select.option></flux:select>
            @if (in_array($eventType, ['added', 'progress'], true) && $obligation->current_subject_quantity !== null)<div><flux:input wire:model="quantity" type="number" step="{{ $obligation->quantityMode()->inputStep() }}" min="{{ $obligation->quantityMode()->isCountable() ? '1' : '0.0001' }}" label="Quantity delivered" /><p class="mt-1 text-xs text-zinc-500">Currently outstanding: {{ \App\Domain\Money\Decimal::display($obligation->current_subject_quantity) }} {{ $obligation->subject_unit }} · {{ $obligation->quantityMode()->isCountable() ? 'whole units only' : 'fractional quantities allowed' }}</p></div>@endif
        @else
            <flux:select wire:model.live="eventType" label="Update type"><flux:select.option value="progress">Progress update</flux:select.option><flux:select.option value="fulfilled">Fulfilled</flux:select.option><flux:select.option value="missed">Missed / delayed</flux:select.option><flux:select.option value="scope_change">Scope changed</flux:select.option><flux:select.option value="waived">Waived / no longer required</flux:select.option><flux:select.option value="note">Note</flux:select.option></flux:select>
        @endif
        <flux:input wire:model="occurredOn" type="date" label="Date" required />
        <flux:textarea wire:model="note" label="Notes" placeholder="What happened, what was agreed, or what evidence should be attached?" rows="4" />
        <flux:button type="submit" variant="primary" class="w-full">Save update</flux:button>
    </form>
</section>
