<div class="mx-auto w-full max-w-2xl">
    <div class="mb-7"><a wire:navigate href="{{ route('financial-profiles.index') }}" class="text-sm text-zinc-500 hover:text-zinc-800 dark:hover:text-zinc-200">← Back to profiles</a><div class="mt-5 flex items-start gap-4"><span class="app-page-icon hidden shrink-0 sm:inline-flex"><flux:icon name="squares-2x2" class="size-6" /></span><div><div class="app-eyebrow">Workspace settings</div><flux:heading size="xl" class="mt-2 text-3xl tracking-tight">Edit profile</flux:heading><flux:text class="mt-2 leading-6">These settings apply to {{ $profile->name }}.</flux:text></div></div></div>
    <form wire:submit="save" class="app-card space-y-5 rounded-2xl p-6 sm:p-7">
        <flux:input wire:model="name" label="Name" required />
        <flux:select wire:model="type" label="Type"><flux:select.option value="personal">Personal</flux:select.option><flux:select.option value="business">Business</flux:select.option><flux:select.option value="family">Family</flux:select.option><flux:select.option value="custom">Custom</flux:select.option></flux:select>
        <flux:select wire:model="baseCurrency" label="Base currency" required>@foreach (\App\Domain\Money\Currency::options() as $code => $label)<flux:select.option value="{{ $code }}">{{ $code }} — {{ $label }}</flux:select.option>@endforeach</flux:select>
        <flux:select wire:model="timezone" label="Timezone" description="Used for due dates, reminders, and date display." searchable required>@foreach (\App\Support\ProfileOptions::timezones() as $value => $label)<flux:select.option value="{{ $value }}">{{ $label }}</flux:select.option>@endforeach</flux:select>
        <flux:select wire:model="locale" label="Locale" description="Controls language and regional formatting when available." searchable><flux:select.option value="">Use the application default</flux:select.option>@foreach (\App\Support\ProfileOptions::locales() as $value => $label)<flux:select.option value="{{ $value }}">{{ $label }}</flux:select.option>@endforeach</flux:select>
        <flux:checkbox wire:model="isIslamicModeEnabled" label="Enable Islamic Mode guidance" />
        <div class="flex justify-end gap-3"><flux:button :href="route('financial-profiles.index')" wire:navigate variant="ghost">Cancel</flux:button><flux:button type="submit" variant="primary">Save changes</flux:button></div>
    </form>

    <livewire:profiles.fx-rates :profile="$profile" :key="'fx-rates-'.$profile->id" />

    @if (session('invitation-created'))<div class="mt-7 rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800 dark:border-emerald-900 dark:bg-emerald-950/30 dark:text-emerald-200">{{ session('invitation-created') }}@if ($invitationUrl)<div class="mt-2 break-all font-mono text-xs">{{ $invitationUrl }}</div>@endif</div>@endif
    @if (session('emergency-access-updated'))<div class="mt-7 rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800 dark:border-emerald-900 dark:bg-emerald-950/30 dark:text-emerald-200">{{ session('emergency-access-updated') }}</div>@endif
    <section class="mt-7 rounded-xl border border-zinc-200 bg-white dark:border-zinc-700 dark:bg-zinc-900"><div class="border-b border-zinc-200 px-5 py-4 dark:border-zinc-700"><flux:heading size="lg">Invite people</flux:heading><flux:text class="mt-1 text-sm">Only the invited email address can accept the link.</flux:text></div><form wire:submit="invite" class="space-y-5 px-5 py-5"><flux:input wire:model="inviteEmail" type="email" label="Email" required /><flux:select wire:model="inviteRole" label="Role"><flux:select.option value="editor">Editor</flux:select.option><flux:select.option value="payment_manager">Payment manager</flux:select.option><flux:select.option value="viewer">Viewer</flux:select.option><flux:select.option value="heir">Heir / emergency representative</flux:select.option></flux:select><flux:button type="submit" variant="primary">Create invitation</flux:button></form><div class="border-t border-zinc-200 px-5 py-4 dark:border-zinc-700"><div class="text-sm font-medium">Current members</div>@forelse ($members as $member)<div class="mt-3 flex justify-between gap-3 text-sm"><span>{{ $member->user->email }}</span><span class="text-zinc-500">{{ ucfirst(str_replace('_', ' ', $member->role)) }}</span></div>@empty<div class="mt-3 text-sm text-zinc-500">No members yet.</div>@endforelse</div></section>
    <section class="mt-7 rounded-xl border border-amber-200 bg-amber-50/70 dark:border-amber-900/70 dark:bg-amber-950/20"><div class="border-b border-amber-200 px-5 py-4 dark:border-amber-900/70"><flux:heading size="lg">Emergency access requests</flux:heading><flux:text class="mt-1 text-sm">Heir representatives remain locked out until you explicitly activate access. The seven-day waiting period must elapse before activation, and access expires after 90 days.</flux:text></div><div class="px-5 py-4">@error('emergencyAccess')<div class="mb-3 rounded-lg bg-rose-100 px-3 py-2 text-sm text-rose-800">{{ $message }}</div>@enderror @forelse ($emergencyRequests as $request)<div class="flex flex-wrap items-center justify-between gap-3 border-b border-amber-200 py-3 last:border-0 dark:border-amber-900/70"><div><div class="font-medium">{{ $request->user->name }} · {{ $request->user->email }}</div><div class="mt-1 text-sm text-amber-900/70 dark:text-amber-100/70">Eligible after {{ $request->activate_after?->format('d M Y, H:i') ?? 'owner review' }}</div></div><div class="flex gap-2"><flux:button size="sm" variant="ghost" wire:click="decideEmergencyAccess('{{ $request->id }}', 'reject')">Reject</flux:button>@if ($request->activate_after === null || $request->activate_after->isPast())<flux:button size="sm" variant="primary" wire:click="decideEmergencyAccess('{{ $request->id }}', 'activate')">Activate</flux:button>@else<flux:button size="sm" variant="primary" disabled>Waiting period</flux:button>@endif</div></div>@empty<div class="text-sm text-amber-900/70 dark:text-amber-100/70">No pending requests.</div>@endforelse</div></section>
</div>
