<section class="rounded-xl border border-zinc-200 bg-white dark:border-zinc-700 dark:bg-zinc-900">
    <div class="border-b border-zinc-200 px-5 py-4 dark:border-zinc-700"><flux:heading size="lg">Communication</flux:heading><flux:text class="mt-1 text-sm">Review every message before sharing or sending.</flux:text></div>
    @if (session('communication-saved'))<div class="mx-5 mt-5 rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800 dark:border-emerald-900 dark:bg-emerald-950/30 dark:text-emerald-200">{{ session('communication-saved') }}</div>@endif
    @if (session('communication-sent'))<div class="mx-5 mt-5 rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800 dark:border-emerald-900 dark:bg-emerald-950/30 dark:text-emerald-200">{{ session('communication-sent') }}</div>@endif
    <form wire:submit="saveDraft" class="space-y-5 px-5 py-5">
        <div class="grid gap-5 sm:grid-cols-2"><flux:select wire:model="channel" label="Channel"><flux:select.option value="whatsapp">WhatsApp share</flux:select.option><flux:select.option value="email">Email</flux:select.option></flux:select><flux:select wire:model.live="template" label="Template">@if ($obligation->obligation_kind === 'money')<flux:select.option value="payment_submitted">Payment submitted</flux:select.option><flux:select.option value="payment_planned">Payment planned</flux:select.option><flux:select.option value="request_balance_confirmation">Request balance confirmation</flux:select.option><flux:select.option value="request_payment_instructions">Request payment instructions</flux:select.option><flux:select.option value="collection_reminder">Collection reminder</flux:select.option>@elseif ($obligation->obligation_kind === 'asset')<flux:select.option value="request_update">Request asset update</flux:select.option><flux:select.option value="return_reminder">Asset return reminder</flux:select.option>@elseif ($obligation->obligation_kind === 'service')<flux:select.option value="request_update">Request service update</flux:select.option><flux:select.option value="service_reminder">Service reminder</flux:select.option>@else<flux:select.option value="request_update">Request progress update</flux:select.option><flux:select.option value="commitment_reminder">Commitment reminder</flux:select.option>@endif<flux:select.option value="settlement_follow_up">Settlement follow-up</flux:select.option></flux:select></div>
        <flux:input wire:model="recipient" label="Recipient" placeholder="Optional for WhatsApp; email required for email" />
        <flux:textarea wire:model="body" label="Message" rows="9" required />
        <div class="flex flex-col gap-3 sm:flex-row sm:justify-end"><flux:button type="submit" variant="primary">Save draft</flux:button>@if ($channel === 'whatsapp' && $whatsappUrl)<a href="{{ $whatsappUrl }}" target="_blank" rel="noopener" class="inline-flex items-center justify-center rounded-lg border border-zinc-300 px-4 py-2 text-sm font-medium hover:bg-zinc-50 dark:border-zinc-600 dark:hover:bg-zinc-800">Open WhatsApp share</a>@endif@if ($channel === 'email')<flux:button type="button" wire:click="sendEmail" variant="ghost">Send email</flux:button>@endif</div>
    </form>
    @if ($messages->isNotEmpty())<div class="border-t border-zinc-200 px-5 py-4 dark:border-zinc-700"><div class="text-sm font-medium">Recent messages</div><div class="mt-3 space-y-3">@foreach ($messages as $message)<div class="rounded-lg bg-zinc-50 px-3 py-3 text-sm dark:bg-zinc-800"><div class="flex justify-between gap-3 text-xs text-zinc-500"><span>{{ ucfirst($message->thread->channel) }} · {{ ucfirst($message->status) }}</span><span>{{ $message->created_at?->format('d M Y H:i') }}</span></div><div class="mt-2 whitespace-pre-line">{{ $message->body }}</div></div>@endforeach</div></div>@endif
</section>
